name: run-app
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # clone repo
      - uses: actions/setup-node@v4 # install node
      - run: make setup # install proj
      - run: make test # run tests
      - run: make lint
      - uses: actions/hexlet-components/hello-from-hexlet-action
